main:
  - name: Industries
    url: /industries/
    weight: 1
  
  - name: Docs
    url: /docs/
    weight: 2

  - name: Showcase
    url: /showcase/
    weight: 3

  - name: Flutter
    url: https://atsign.dev/
    weight: 4

  - name: Tools
    url: /tools/
    weight: 5